name: Test build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pandoc latexmk
          sudo apt-get install texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
      - name: Build docs
        run: sphinx-build docs/source docs/build/html
